#!/bin/sh
set -e
set -u

# shellcheck disable=SC2034
OAUTH2_PROXY_PARAMS="--config /config/oauth2-proxy.cfg"

# Enable debug mode?
if is-bool-val-true "${OAUTH2_PROXY_DEBUG:-0}"; then
    OAUTH2_PROXY_PARAMS="${OAUTH2_PROXY_PARAMS} --logging.level=debug"
fi
