#!/bin/sh
set -e
set -u

printf '%s\n' "--config"
printf '%s\n' "/config/oauth2-proxy.cfg"
printf '%s\n' "--http-address=unix:///tmp/oauth2-proxy.sock"

# Enable debug mode?
if is-bool-val-true "${CONTAINER_DEBUG:-0}"; then
  printf '%s\n' "--logging-level=debug"
fi
